### ISSUE TITLE
[Feat] Quiz 타입 정의 및 기본 인터페이스 정의

### ISSUE THREAD

**Issue by mrbartrns** [prgrms-fe-devcourse/FEDC2_CheQuiz_Gidong#3]
## ✏️ 작업 내용

퀴즈 풀기, 퀴즈 결과 페이지를 위한 퀴즈 타입 정의 및 기본 인터페이스를 정의합니다.

## ⚠️ 주의사항

퀴즈와 관련되지 않은 API는 퀴즈 연결을 위하여 API 명세서에 있는 내용을 단순히 연결할 예정이니, 해당 API를 직접 사용시 추가적인 조치가 필요합니다.

## ⏰ 예상 시간

1H

## 🔎 추가 정보
중요한 부분인 것 같아서 먼저 작업한 뒤 나머지 부분 작업하겠습니다.

**Comment by padd60** [comment]
타입은 interface 폴더에 파일명.d.ts 생성하시고 export 해서 관리하게 끔 스켈레톤 형성되어있습니다.
더 좋은 방안이 있다면 준혁님이 스케폴딩 커스텀 하고 PR때 커맨트 남겨주세요~
